version: '3.1'
services:
  API:
    container_name: 'DrakeAPI'
    image: 'drake-rest-api-image'
    ports:
      - "8082:8080"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop


  PostgreSQL:
    container_name: 'DrakeAPI_PostgreSQL'
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
